#[î‚¶](#16A085)\
format = """
[â–Šâ–Š](fg:#06969A)\
$shell\
[î‚°](fg:#be2edd bg:#16A085)\
$username\
[î‚°](fg:#16A085 bg:#DA627D)\
$directory\
[î‚°](fg:#DA627D bg:#F19066)\
$git_branch\
[î‚°](fg:#F19066 bg:#0097a7)\
$git_status\
[î‚°](fg:#0097a7 bg:#e84393)\
$c\
$cmake\
$java\
$rust\
$lua\
$python\
$golang\
[î‚°](fg:#e84393 bg:#06969A)\
$battery\
[î‚°](fg:#06969A bg:#33658A)\
$time\
[î‚´](#33658A)
[â–Šâ–Š](fg:#06969A)\
[î‚°](fg:#F19066 bg:#e84393)\
[î‚°](fg:#e84393 bg:#06969A)\
[î‚°](fg:#06969A bg:#e84393)\
[î‚°](fg:#e84393 bg:#06969A)\
[î‚° ](fg:#06969A)\
"""
#$docker_context\
#[î‚°](fg:#06969A bg:#33658A)\
#[î‚µî‚µ](fg:#33658A)\
#[î‚µî‚µ ](fg:#fc7d98)\

# Use custom format
#format = """
#[â”Œâ”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€>](bold green)
#[â”‚](bold green)$directory$rust$package
#[â””â”€>](bold green) """

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Inserts a blank line between shell prompts
add_newline = false

[battery]
full_symbol = "ğŸ”‹"
charging_symbol = "âš¡ï¸"
discharging_symbol = "ğŸ’€"
disabled = true

[[battery.display]] # "bold yellow" style and ğŸ’¦ symbol when capacity is between 10% and 30%
threshold = 10
style = "bg:#06969A"
discharging_symbol = "ğŸ’¦"
# when capacity is over 30%, the battery indicator will not be displayed

# Disable the blank line at the start of the prompt
add_newline = false

[shell]
format = "[ $indicator ]($style)"
fish_indicator = "ïœ¹"
bash_indicator = "î•"
zsh_indicator = "î•"
powershell_indicator = "ï‘ _"
unknown_indicator = "mystery shell"
style = "bg:#be2edd fg:#dcdde1"
disabled = false

# You can also replace your username with a neat symbol like ï„  to save some space
[username]
show_always = true
style_user = "bg:#16A085 fg:#37474F"
style_root = "bg:#16A085 fg:#37474F"
format = '[ ä¸ ]($style)'
#format = '[ $user ]($style)'

[directory]
style = "bg:#DA627D fg:#263238"
read_only_style = "bg:#DA627D fg:#263238"
format = "[$path]($style)[ $read_only]($read_only_style)"
truncation_length = 5
truncation_symbol = "â€¦/"
home_symbol = "ğŸ "
truncate_to_repo = false
use_logical_path = true

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "ïœ˜ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "
"Video" = "ğŸ“¹"
#"~/.dotfiles" = "ğŸ /.dotfiles"
#".dotfiles" = "â¤ï¸ "
# Keep in mind that the order matters. For example:
# "Important Documents" = " ïœ˜ï„ª "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important ïœ˜ " = " ïœ˜ï„ª "

[c]
symbol = "î˜"
style = "bg:#e84393"
format = '[ $symbol ($version) ]($style)'

[cmake]
symbol = " î˜•"
style = "bg:#e84393 fg:#34495e"
#format = '[ $symbol ($version) ]($style)'
format = '[$symbol ($version(-$name)) ]($style)'

[docker_context]
symbol = "ïŒˆ "
style = "bg:#06969A"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = "î‰µ "
style = "bg:#e84393"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = "î˜¬ "
style = "bg:#e84393"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = "ï˜"
style = "bg:#F19066 fg:#151D29"
format = '[ $symbol $branch ]($style)'

[git_status]
#style = "bg:#F19066 fg:#2e2c50"
style = "bg:#0097a7 fg:#002b36"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = "î˜§ "
style = "bg:#e84393"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = "î˜† "
style = "bg:#e84393 fg:#535164"
format = '${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
python_binary = "python3"

[lua]
symbol = "î˜ "
style = "bg:#e84393 fg:#535164"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = "î· "
style = "bg:#e84393"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = "î‰– "
style = "bg:#e84393"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = "î˜¤ "
style = "bg:#e84393"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = "îœ˜"
style = "bg:#e84393"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "ïš¤ "
style = "bg:#e84393"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = "î¨"
style = "bg:#e84393"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = "îœ· "
style = "bg:#e84393"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#33658A"
#format = '[ â™¥ $time ]($style)'
#format = '[ ğŸ• $time ]($style)'
format = '[ ğŸ•°ï¸ $time  ]($style)'
